### ISSUE TITLE
Crash when click on Piko mod settings   

### ISSUE THREAD

**Issue by ii1ddi** [crimera/piko#121]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.twitter.android/app.revanced.integrations.twitter.settings.SettingsActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x0

	at android.app.ActivityThread.performLaunchActivity(Unknown Source:621)
	at android.app.ActivityThread.handleLaunchActivity(Unknown Source:47)
	at android.app.servertransaction.LaunchActivityItem.execute(Unknown Source:63)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:77)
	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:73)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:43)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loop(Unknown Source:242)
	at android.app.ActivityThread.main(Unknown Source:101)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
	at android.content.res.Resources.getText(Unknown Source:36)
	at android.content.res.MiuiResources.getText(Unknown Source:11)
	at android.content.res.Resources.getString(Unknown Source:0)
	at app.revanced.integrations.shared.Utils.getResourceString(Utils.java:186)
	at app.revanced.integrations.twitter.settings.SettingsActivity$Screen.strRes(SettingsActivity.java:478)
	at app.revanced.integrations.twitter.settings.SettingsActivity$Screen.onCreate(SettingsActivity.java:349)
	at android.app.Fragment.performCreate(Unknown Source:13)
	at android.app.FragmentManagerImpl.moveToState(Unknown Source:357)
	at android.app.FragmentManagerImpl.addAddedFragments(Unknown Source:46)
	at android.app.FragmentManagerImpl.executeOpsTogether(Unknown Source:129)
	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(Unknown Source:99)
	at android.app.FragmentManagerImpl.execPendingActions(Unknown Source:21)
	at android.app.FragmentManagerImpl.dispatchMoveToState(Unknown Source:18)
	at android.app.FragmentManagerImpl.dispatchActivityCreated(Unknown Source:4)
	at android.app.FragmentController.dispatchActivityCreated(Unknown Source:4)
	at android.app.Activity.performCreate(Unknown Source:67)
	at android.app.Activity.performCreate(Unknown Source:1)
	at android.app.Instrumentation.callActivityOnCreate(Unknown Source:3)
	at android.app.ActivityThread.performLaunchActivity(Unknown Source:376)
	... 11 more

**Comment by crimera** [comment]
This should be fixed with the latest patches build. could you check if the crash still occurs for you?
