### ISSUE TITLE
App crash 

### ISSUE THREAD

**Issue by zi00duck** [crimera/piko#246]
time: 1717100683608
msg: java.lang.UnsupportedOperationException: Binary XML file line #4: You must supply a layout_height attribute., theme={InheritanceMap=[id=0x7f140399com.twitter.android:style/PromotedBadge.Control], Themes=[com.twitter.android:style/PromotedBadge.Control, forced, com.twitter.android:style/ThemeOverlay.TypefaceExperiment.Enabled, forced, com.twitter.android:style/TweetsTheme, forced, com.twitter.android:style/Twitter.LightsOut, forced, com.twitter.android:style/Twitter, forced, com.twitter.android:style/Theme, forced, com.twitter.android:style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.twitter.android/com.twitter.android.onboarding.core.entertext.EnterTextSubtaskActivity}: android.view.InflateException: Binary XML file line #13 in com.twitter.android:layout/ocf_subtask_container_with_toolbar: Binary XML file line #4: You must supply a layout_height attribute., theme={InheritanceMap=[id=0x7f140399com.twitter.android:style/PromotedBadge.Control], Themes=[com.twitter.android:style/PromotedBadge.Control, forced, com.twitter.android:style/ThemeOverlay.TypefaceExperiment.Enabled, forced, com.twitter.android:style/TweetsTheme, forced, com.twitter.android:style/Twitter.LightsOut, forced, com.twitter.android:style/Twitter, forced, com.twitter.android:style/Theme, forced, com.twitter.android:style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3655)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7937)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)
Caused by: android.view.InflateException: Binary XML file line #13 in com.twitter.android:layout/ocf_subtask_container_with_toolbar: Binary XML file line #4: You must supply a layout_height attribute., theme={InheritanceMap=[id=0x7f140399com.twitter.android:style/PromotedBadge.Control], Themes=[com.twitter.android:style/PromotedBadge.Control, forced, com.twitter.android:style/ThemeOverlay.TypefaceExperiment.Enabled, forced, com.twitter.android:style/TweetsTheme, forced, com.twitter.android:style/Twitter.LightsOut, forced, com.twitter.android:style/Twitter, forced, com.twitter.android:style/Theme, forced, com.twitter.android:style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
Caused by: java.lang.UnsupportedOperationException: Binary XML file line #4: You must supply a layout_height attribute., theme={InheritanceMap=[id=0x7f140399com.twitter.android:style/PromotedBadge.Control], Themes=[com.twitter.android:style/PromotedBadge.Control, forced, com.twitter.android:style/ThemeOverlay.TypefaceExperiment.Enabled, forced, com.twitter.android:style/TweetsTheme, forced, com.twitter.android:style/Twitter.LightsOut, forced, com.twitter.android:style/Twitter, forced, com.twitter.android:style/Theme, forced, com.twitter.android:style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
	at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:839)
	at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:8231)
	at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:8428)
	at androidx.constraintlayout.widget.ConstraintLayout$a.<init>(Twttr:1)
	at androidx.constraintlayout.widget.ConstraintLayout.generateLayoutParams(Twttr:1)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1137)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1275)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1131)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at dc9.inflate(Twttr:5)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
	at xjr.<init>(Twttr:6)
	at w8s.<init>(Twttr:1)
	at gdq.<init>(Twttr:1)
	at com.twitter.app.di.app.DaggerTwApplOG$up$a.get(Twttr:831)
	at tb9.get(Twttr:14)
	at com.twitter.app.di.app.DaggerTwApplOG$up$a.get(Twttr:840)
	at tb9.get(Twttr:14)
	at com.twitter.app.di.app.DaggerTwApplOG$up$a.get(Twttr:921)
	at tb9.get(Twttr:14)
	at com.twitter.app.di.app.DaggerTwApplOG$up$a.get(Twttr:934)
	at tb9.get(Twttr:14)
	at com.twitter.app.di.app.DaggerTwApplOG$up$a.get(Twttr:422)
	at tb9.get(Twttr:14)
	at com.twitter.app.di.app.DaggerTwApplOG$up.b(Twttr:15)
	at e9.b(Twttr:87)
	at ao.e(Twttr:49)
	at c0e.onCreate(Twttr:6)
	at android.app.Activity.performCreate(Activity.java:8360)
	at android.app.Activity.performCreate(Activity.java:8339)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1423)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3636)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7937)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)

**Comment by rushiiMachine** [comment]
I used antisplit to merge splits back together, and patching that seemed to fix this 👍
