### ISSUE TITLE
Latest version patch failed. PathNotFoundException

### ISSUE THREAD

**Issue by tonyser96** [crimera/piko#378]
- Device Info
ReVanced Manager: 1.21.2
Model: PGT-N19
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.twitter.android v10.56.0-release.0 (Suggested: Any)
Patches version: v1.39.0
Patches added: Bring back twitter
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: false
Patches source: crimera/piko
Integration source: crimera/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 56 patches
Compiling patched dex files
Compiled 12 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~jw3kwU1KxHG88OWpv9uh7A==/app.revanced.manager.flutter-lkIuE6Fp0PWl86Bs0zwQXw==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QGXUWC/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QGXUWC/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:462)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~jw3kwU1KxHG88OWpv9uh7A==/app.revanced.manager.flutter-lkIuE6Fp0PWl86Bs0zwQXw==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QGXUWC/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QGXUWC/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
	... 7 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QGXUWC/out.apk' (OS Error: No such file or directory, errno = 2)

**Comment by tonyser96** [comment]
Re opening since I'm facing the same issue again. 

The latest patch was successfully patched on my cli... 

The reason that I used it instead of RVX manager 1.22 is because for some reason I got this error on the manager app, even with the latest piko release. I've reported it a few months ago here.  A new patch later fixed it, then it broke again a few patches ago:

An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~JGDsO3qiuK053QiMGaa-UA==/app.rvx.manager.flutter-qXpP-wQsTx1kCo6FAnn8hQ==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.rvx.manager.flutter/files/patcher/tmp-SQVUQP/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.rvx.manager.flutter/files/patcher/tmp-SQVUQP/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(SourceFile:123)
	at brut.androlib.AaptInvoker.invokeAapt(SourceFile:394)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:134)
	at app.revanced.patcher.Patcher.get(SourceFile:268)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(SourceFile:343)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$7KobHryxqqdI5JS3uiaGATjlYU8(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda2.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~JGDsO3qiuK053QiMGaa-UA==/app.rvx.manager.flutter-qXpP-wQsTx1kCo6FAnn8hQ==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.rvx.manager.flutter/files/patcher/tmp-SQVUQP/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.rvx.manager.flutter/files/patcher/tmp-SQVUQP/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(SourceFile:104)
	at brut.androlib.AaptInvoker.invokeAapt2(SourceFile:119)
	... 7 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.rvx.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.rvx.manager.flutter/files/patcher/tmp-SQVUQP/out.apk' (OS Error: No such file or directory, errno = 2)

Maybe I should create a separate issue for this though, but due to it's similarity, I thought commenting on my old issue might be better.

There had been a similar issue reported on RVX github, but was immediately closed, and OP was told to refer to the specific patch repo instead.
