### ISSUE TITLE
cant patch 10.70.0 with rvx manager

### ISSUE THREAD

**Issue by isillo** [crimera/piko#490]
crashes during compiling, ser log from revanced extended manager:

- Device Info
RVX Manager: 1.22.2
Model: SM-S918B
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.twitter.android v10.70.0-release.0 (Suggested: Any)
Patches version: v1.46.0
Patches added: Default
Patches removed: Customize explore tabs
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: false
Remove unused library: true
Use pre-release: false
Patches source: crimera/piko
Integration source: crimera/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 60 patches
Compiling patched dex files
Compiled 12 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~3y58kgX1NFq2H1LqSN_21A==/app.rvx.manager.flutter--gzE7-pOaupRXs6HpSnIcA==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.rvx.manager.flutter/files/patcher/tmp-PIOYZW/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 310700000, --version-name, 10.70.0-release.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.rvx.manager.flutter/cache/APKTOOL4035325988854616490.tmp, -0, arsc, -I, /data/user/0/app.rvx.manager.flutter/files/patcher/tmp-PIOYZW/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.rvx.manager.flutter/files/patcher/tmp-PIOYZW/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.rvx.manager.flutter/files/patcher/tmp-PIOYZW/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(SourceFile:249)
	at brut.androlib.AaptInvoker.invokeAapt(SourceFile:394)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:134)
	at app.revanced.patcher.Patcher.get(SourceFile:268)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(SourceFile:343)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$7KobHryxqqdI5JS3uiaGATjlYU8(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda2.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~3y58kgX1NFq2H1LqSN_21A==/app.rvx.manager.flutter--gzE7-pOaupRXs6HpSnIcA==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.rvx.manager.flutter/files/patcher/tmp-PIOYZW/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 310700000, --version-name, 10.70.0-release.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.rvx.manager.flutter/cache/APKTOOL4035325988854616490.tmp, -0, arsc, -I, /data/user/0/app.rvx.manager.flutter/files/patcher/tmp-PIOYZW/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.rvx.manager.flutter/files/patcher/tmp-PIOYZW/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.rvx.manager.flutter/files/patcher/tmp-PIOYZW/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(SourceFile:104)
	at brut.androlib.AaptInvoker.invokeAapt2(SourceFile:245)
	... 7 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.rvx.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.rvx.manager.flutter/files/patcher/tmp-PIOYZW/out.apk' (OS Error: No such file or directory, errno = 2)

**Comment by tonyser96** [comment]
patch also fails using the cli tool (in my laptop) as well...

WARNING: error: failed linking references. 
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/qw/kw24qrnn3ljdrdq15y9jz7h00000gn/T/brut_util_Jar_50459412254991541718866495853015084434.tmp, link, -o, /twitter-revanced_v10.70.0-release.0_v1.46.0-temporary-files/patcher/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 310700000, --version-name, 10.70.0-release.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /var/folders/qw/kw24qrnn3ljdrdq15y9jz7h00000gn/T/APKTOOL15694743455053349687.tmp, -0, arsc, -I, /twitter-revanced_v10.70.0-release.0_v1.46.0-temporary-files/patcher/1.apk, --manifest, /twitter-revanced_v10.70.0-release.0_v1.46.0-temporary-files/patcher/apk/AndroidManifest.xml, /twitter-revanced_v10.70.0-release.0_v1.46.0-temporary-files/patcher/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:249)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:394)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:134)
	at app.revanced.patcher.Patcher.get(Patcher.kt:268)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:312)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/qw/kw24qrnn3ljdrdq15y9jz7h00000gn/T/brut_util_Jar_50459412254991541718866495853015084434.tmp, link, -o, /twitter-revanced_v10.70.0-release.0_v1.46.0-temporary-files/patcher/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 310700000, --version-name, 10.70.0-release.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /var/folders/qw/kw24qrnn3ljdrdq15y9jz7h00000gn/T/APKTOOL15694743455053349687.tmp, -0, arsc, -I, /twitter-revanced_v10.70.0-release.0_v1.46.0-temporary-files/patcher/1.apk, --manifest, /twitter-revanced_v10.70.0-release.0_v1.46.0-temporary-files/patcher/apk/AndroidManifest.xml, /twitter-revanced_v10.70.0-release.0_v1.46.0-temporary-files/patcher/apk/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:245)
	... 13 more
